version: '3.1'
services:
  web:
    image: victorqueirogabr/screentodb
    volumes:
      - ./app:/var/www/html
    build:
      context: .  # O contexto do build deve apontar para o diretório com o Dockerfile do Easy!Appointments
    ports:
      - "80:80"
    environment:
      DB_HOST: 'mysql'
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  app:
  mysql: {}